name: Deploy to STAGING

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to STAGING
        run: echo "🚀 Deploying to STAGING environment"
